config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'

  get :search, to: 'search#index'
  post :search, to: 'search#index'

  resources :courses
  resources :subjects
  resources :instructors

  resources :users do
    collection do
      post :register_course
      post :drop_course
    end
  end
  resources :sessions do
    collection do
      get :login
      delete :destroy
    end
  end

  # resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: %i[ show edit update destroy ]

  # GET /courses or /courses.json
  def index
    if params[:registered].present?
      @courses = current_user.courses
      @my_course = true
    else
      @courses = Course.all
    end
    @courses = @courses.order(:id).page(params[:page]).per(10)
  end

  # GET /courses/1 or /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses or /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: "Course was successfully created." }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1 or /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: "Course was successfully updated." }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1 or /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: "Course was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:code, :name, :description, :independent_study, :requirements)
    end
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_column.html.slim
td = course.code
td = course.name
td = course.description
td = course.independent_study.to_s.upcase
- if logged_in?
  - if user_courses.include?(course.id)
    td = link_to 'Drop', drop_course_users_path(course_id: course.id), method: :post, remote: true, data: { confirm: 'Are you sure?' }
  - else
    td = link_to 'Enroll', register_course_users_path(course_id: course.id), method: :post, remote: true, data: { confirm: 'Are you sure?' }

app/views/courses/_form.html.erb
<%= form_with(model: course) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :code %>
    <%= form.text_field :code %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :independent_study %>
    <%= form.check_box :independent_study %>
  </div>

  <div class="field">
    <%= form.label :requirements %>
    <%= form.text_field :requirements %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/courses/_table.html.slim
- if logged_in?
  - user_courses = current_user.courses.pluck(:id)
- else
  - user_courses = []
table.table
  thead
    tr
      th.col-md-1 scope='col' Code
      th.col-md-2 scope='col' Name
      th.col-md-3 scope='col' Description
      th.col-md-2 scope='col' Independent study
      - if logged_in?
        th.col-md-1 scope='col' colspan='3' Actions

  tbody
    - if courses
      - courses.each do |course|
        tr class="course-#{course.id}"
          = render partial: 'courses/column', locals: {course: course, user_courses: user_courses}

- if courses.respond_to?(:current_page)
  = paginate courses, theme: 'bootstrap-5'

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.slim
p#notice
  = notice
- if @my_course
  h1 My Courses
- else
  h1 Courses
/= link_to 'New Course', new_course_path
.course-table
  = render partial: 'courses/table', locals: {courses: @courses}

app/views/courses/new.html.erb
<h1>New Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Back', courses_path %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Code:</strong>
  <%= @course.code %>
</p>

<p>
  <strong>Name:</strong>
  <%= @course.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @course.description %>
</p>

<p>
  <strong>Independent study:</strong>
  <%= @course.independent_study %>
</p>

<p>
  <strong>Requirements:</strong>
  <%= @course.requirements %>
</p>

<%= link_to 'Edit', edit_course_path(@course) %> |
<%= link_to 'Back', courses_path %>