config/routes.rb
Rails.application.routes.draw do
  root 'courses#index'

  get :search, to: 'search#index'
  post :search, to: 'search#index'

  resources :courses
  resources :subjects
  resources :instructors

  resources :users do
    collection do
      post :register_course
      post :drop_course
    end
  end
  resources :sessions do
    collection do
      get :login
      delete :destroy
    end
  end

  # resources :sessions
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/layouts/_navbar.html.slim
nav.navbar.navbar-expand-lg.navbar-light.bg-light
  .container-fluid
    - if logged_in?
      = link_to 'My Courses', courses_path(registered: true), class: "navbar-brand"
    - else
      = link_to 'My Courses', login_sessions_path, remote: true, class: "navbar-brand"
    .collapse.navbar-collapse#navbarText
      ul.navbar-nav.me-auto.mb-2.mb-lg-0
        li.nav-item
          = link_to :Search, search_path, class: "nav-link"
        li.nav-item
          = link_to :Courses, courses_path, class: "nav-link"
        li.nav-item
          = link_to :Instructors, instructors_path, class: "nav-link"
    - if logged_in?
      = link_to 'Sign out', sessions_path, method: :delete, remote: true, data: { confirm: 'Are you sure?' }
    - else
      = link_to 'Sign in', login_sessions_path, remote: true

app/views/layouts/application.html.slim
doctype html
html
  head
    title Zhendong Yin
    meta name="viewport" content="width=device-width,initial-scale=1"
    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"
    script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/bQdsTh/da6pkI1MST/rWKFNjaCP5gBSY4sEBT38Q/9RBh9AH40zEOg7Hlq2THRZ" crossorigin="anonymous"


  body
    .be-wrapper.be-fixed-sidebar
    .body_navbar
      = render partial: 'layouts/navbar'
    .container
      = yield